/// Generated by AssetsRefGenerator on 2020/12/26
class Res {
  static const String blood = "images/blood.png";
  static const String Maps = "images/Maps.png";
  static const String yellow = "images/yellow.png";
}
